// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drweqtunimvjossagnlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyd2VxdHVuaW12am9zc2FnbmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTMzODAsImV4cCI6MjA2NTI4OTM4MH0.x7HEUWVfgT2ke_hJF9cM04_LS3xHpF8TrY-v6eBxN4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);